CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C ODE TO BE INTEGRATED BY FOURTH-ORDER RK METHOD
      SUBROUTINE FUNC_RK(NEQ,X,Y,DELTAY,H)
      IMPLICIT REAL*8(A-H,O-Z)
C FOR ME, A = 10
      REAL :: A = 10
      REAL*8 :: Y(NEQ),DELTAY(10)
      DELTAY(1) = Y(2) * H
      DELTAY(2) = Y(3) * H
      DELTAY(3) = Y(4) * H
      DELTAY(4) = A * X * Y(1) * Y(2) ** 2 / Y(3) * H
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C FOURTH-ORDER RUNGE KUTTA INTEGRATION ROUTINE
      SUBROUTINE RUNGE(NEQ,X,Y,H)
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 Y(NEQ),DELTAY1(10),DELTAY2(10),DELTAY3(10),
     1DELTAY4(10),Z(10)
C FIRST STEP
      DO I = 1, NEQ
          Z(I) = Y(I)
      ENDDO
      CALL FUNC_RK(NEQ,X,Z,DELTAY1,H)
C SECOND STEP
      DO I = 1, NEQ
          Z(I) = Y(I) + DELTAY1(I) / 2.
      ENDDO
      X = X + H / 2.
      CALL FUNC_RK(NEQ,X,Z,DELTAY2,H)
C THIRD STEP
      DO I = 1, NEQ
          Z(I) = Y(I) + DELTAY2(I) / 2.
      ENDDO
      CALL FUNC_RK(NEQ,X,Z,DELTAY3,H)
C FOURTH STEP
      DO I = 1, NEQ
          Z(I) = Y(I) + DELTAY3(I)
      ENDDO
      X = X + H / 2.
      CALL FUNC_RK(NEQ,X,Z,DELTAY4,H)
C SUMMARY
      DO I = 1, NEQ
          Y(I) = Y(I) + (DELTAY1(I) + 2. * DELTAY2(I) + 2. * DELTAY3(I)+
     1    DELTAY4(I)) / 6.
      ENDDO
      RETURN
      END
      
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C THIS IS THE MAIN ROUTIN
      PROGRAM MAIN
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8 Y(4),DY(4)
      !WRITE(*,*) "ENTER NMAX:"
      !READ(*,*) NMAX
      OPEN(UNIT=10,FILE='PA_OUT.TXT')
      WRITE(10,200) "NSTEPS","Y(1)","Y'(1)"
      DO NSTEPS = 1,41,4
          XMAX = 1.
          H = XMAX / NSTEPS
          NEQ = 4
C RK INTEGRATION LOOP
          Y(1) = 1.
          Y(2) = 6.
          Y(3) = 15.
          Y(4) = 10.
          X = 0.
C OPEN A FILE TO WRITE THE RESULTS
          DO I = 1, NSTEPS
              CALL RUNGE(NEQ,X,Y,H)
C COMPARE RESULTS TO ANALYTUCAL EXPRESSION
          ENDDO
          WRITE(10,100) NSTEPS,Y(1),Y(2)
      ENDDO
C THIS IS THE OUTPUT FORMAT
100   FORMAT(I16.3,2(F10.4))
200   FORMAT(3(A12))
      STOP
      END